import { Inter } from "next/font/google";
import { GoogleOAuthProvider } from '@react-oauth/google';
import { ThemeProvider } from 'next-themes';
import Navbar from './navbar/page';
import DynamicBreadcrumb from './breadcrumb/page';
import BottomNav from './bottomnav/page'; // 確保路徑正確
import "./globals.css";
const inter = Inter({ subsets: ["latin"] });

const APP_NAME = "Meowtrade";
const APP_DEFAULT_TITLE = "Meowtrade";
const APP_TITLE_TEMPLATE = "%s - Meowtrade";
const APP_DESCRIPTION = "Generated by create next app";

export const metadata = {
  applicationName: APP_NAME,
  title: {
    default: APP_DEFAULT_TITLE,
    template: APP_TITLE_TEMPLATE,
  },
  description: APP_DESCRIPTION,
  manifest: "/manifest.json",
  appleWebApp: {
    capable: true,
    statusBarStyle: "default",
    title: APP_DEFAULT_TITLE,
    // startUpImage: [],
  },
  formatDetection: {
    telephone: false,
  },
  openGraph: {
    type: "website",
    siteName: APP_NAME,
    title: {
      default: APP_DEFAULT_TITLE,
      template: APP_TITLE_TEMPLATE,
    },
    description: APP_DESCRIPTION,
  },
  twitter: {
    card: "summary",
    title: {
      default: APP_DEFAULT_TITLE,
      template: APP_TITLE_TEMPLATE,
    },
    description: APP_DESCRIPTION,
  },
};
export const viewport = {
  themeColor: "#FFFFFF",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider attribute="class">
          <GoogleOAuthProvider clientId={process.env.NEXT_PUBLIC_GOOGLE_CLIENT_ID}>
            <Navbar />
            <main className="container mx-auto mt-4 pb-16"> {/* 添加 pb-16 來為底部導航騰出空間 */}
              <DynamicBreadcrumb />
              {children}
            </main>
            <BottomNav />
          </GoogleOAuthProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}